name: Deploying

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          script: sh deploy.sh
