# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: multiuseapp   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Download Certs
      run: |
        cd ..
        mkdir sslcert
        cd sslcert
        wget 'https://drive.google.com/file/d/1k4NkKyGzlSHwuIClmSJ4rBvkc5j6iiOz/view?usp=sharing' -O multiuseapp.cer
        wget 'https://drive.google.com/file/d/1T7TO96C_EIWfeshn94HVIKZMb4Ik979p/view?usp=sharing' -O multiuseapp_ddns_net.pem
        wget 'https://drive.google.com/file/d/1Dbz3-UZ63LrR_sIqoIoshxTTrPMthew5/view?usp=sharing' -O multiuseapp.key
        wget 'https://drive.google.com/file/d/1i0bSfLsPY3VRaotq6uhcsRA7h8qRJc4d/view?usp=sharing' -O multiuseapp_ddns_net.pem-chain

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}