# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node building

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Download Certs
      run: |
        cd ..
        touch secret.pem
        echo "${{ secrets.AWS_KEY }}" >> secret.pem
        chmod 400 secret.pem
        scp secret.pem -o StrictHostKeyChecking=no ${{secrets.AWS_USER}}@"${{ secrets.AWS_HOST }}":/Documents/GitHub/sslcert ./
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
