on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: SonarCloud Scan
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Download Certs
      run: |
        sudo apt-get update -y
        sudo apt install python3-pip -y
        pip install gdown
        cd ..
        mkdir sslcert
        cd sslcert
        gdown 'https://drive.google.com/file/d/1k4NkKyGzlSHwuIClmSJ4rBvkc5j6iiOz/view?usp=sharing'
        gdown 'https://drive.google.com/file/d/1T7TO96C_EIWfeshn94HVIKZMb4Ik979p/view?usp=sharing' 
        gdown 'https://drive.google.com/file/d/1Dbz3-UZ63LrR_sIqoIoshxTTrPMthew5/view?usp=sharing'
        gdown 'https://drive.google.com/file/d/1i0bSfLsPY3VRaotq6uhcsRA7h8qRJc4d/view?usp=sharing'
    - name: Install dependencies
      run: npm i nyc --save-dev
    - name: Test Coverage
      run: npm test
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
