on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: SonarCloud Scan
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Download Certs
      run: |
        cd ..
        touch secret.pem
        echo "${{ secrets.INSTANCE_KEY }}" >> secret.pem
        chmod 400 secret.pem
        scp -r -i secret.pem -o StrictHostKeyChecking=no ${{secrets.AWS_USER}}@"${{ secrets.AWS_HOST }}":/Documents/GitHub/sslcert ./
    - name: Install dependencies
      run: npm i nyc --save-dev
    - name: Test Coverage
      run: npm test
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
